version: "3"
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - "./data:/data"
      - "./zims:/zims"

  redis:
    image: redis/redis-stack:7.4.0-v1
    container_name: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    env_file:
      - .env

volumes:
  redis_data: